### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by MickeyFIN** [tr4wzified/KnowYourEnemyPatcher#21]
Know Your Enemy got a rather big update a few days ago and the current patcher doesn't work properly with the latest version of the mod. Hoping this gets updated.

**Comment by Heartbreaker714** [comment]
+1 for this. The update is pretty significant

**Comment by tr4wzified** [comment]
Currently I don't have the time to work on it, I'll look at it when I do have some time on my hands. PRs are welcome in the meantime.

**Comment by tr4wzified** [comment]
Woops, didn't mean to close - wrong button :P

**Comment by Glanzer-modder** [comment]
Why doesn't the patcher work correctly for the latest version of KYE? Seems to work for me as long as you put the KYE Synthesis patcher FIRST in your list. See issue #20 ("Error Message") for more info.

**Comment by tr4wzified** [comment]
Should be updated thanks to @theSkyseS - use the `kye8` branch to access the old version of the patcher if people still want to use previous versions of KYE.
