### ISSUE TITLE
Know Your Enemy is now ESL so the formids changed

### ISSUE THREAD

**Issue by Glanzer-modder** [tr4wzified/KnowYourEnemyPatcher#27]
Hi tr4wzified, looks like version 9.2.0 of kye was converted to ESL so the formids changed. Looks like you've segregated all the formids in your patcher into individual files [here](https://github.com/tr4wzified/KnowYourEnemyPatcher/tree/master/KnowYourEnemyMutagen/FormKeys/KnowYourEnemy) so it should just be a matter of updating the formids in those files, right? Thanks for your help!

**Comment by Drunkender** [comment]
https://github.com/tr4wzified/KnowYourEnemyPatcher/pull/28

**Comment by tr4wzified** [comment]
Merged! Let me know if that resolved the issue, unfortunately away from home for a bit and it's hard for me to test

**Comment by Glanzer-modder** [comment]
Awesome, thanks. I'll test it as soon as I update my Spell Research patch for KYE and a couple other small KYE patches that need updated for the new 9.2 version.

**Comment by Glanzer-modder** [comment]
I just realized I never came back here to post the results of my testing. The updated patcher runs great and I got no errors with the new version of KYE. Thanks for your great support.
